variables:
  GIT_DEPTH: 2
default:
  image: golang:1.13
test:
  script:
    - make docker-test
deploy:
  stage: deploy
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - DECIMAL_CI_COMMIT_TAG=$(echo "$CI_COMMIT_TAG" | tail -c +2)
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$DECIMAL_CI_COMMIT_TAG
  only:
    - tags
